# The Minimal-Theme most used parameters
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

title: 
  en: "DPS-Agents Framework"
  es: "Marco de Agentes-DPS"

# trademark: ""                 #  "<sup>&reg;</sup>"
trademark: "<sup>&copy;</sup>"

subtitle:
  en: "Distributed problem solving with JADE Agents"
  es: "Resolución distribuida de problemas con Agentes JADE"


index:
  en: index.html
  es: index_es.html

lang: en

author: 'Aguayo-Canela, Francisco J.'
author2: 'Garcia-Rodriguez, Isaias'
email: 'francisco -dot- aguayo -At- ieee.org'

description:
  en: Distributed problem solving with JADE Agents. Four implemented agents; a Development micro-Environment that facilitates the deployment of these agents in JADE platform to create large communities and; some interesting examples.
  es: Resolución distribuida de problemas con Agentes JADE. Cuatro agentes implementados; un micro-Entorno de Desarrollo que facilita el despliegue de esos agentes en la plataforma JADE para crear grandes comunidades y; algunos ejemplos interesantes.
  

feed:
  en: /feed.xml
  es: /feed_es.xml

baseurl: ""
url: "https://dpsframework.org" 
hard_url: "https://dpsframework.org"


github:
  owner_url: "https://dpsframework.github.io/"
  repository_url: "https://github.com/dpsframework"
  owner_name: "Francisco J. Aguayo-Canela"
  project_tagline: "1.7"
  name: github
  is_project_page: true
  repository_name: dpsframework

# social links
github_username:  dpsframework
rss: rss
linkedin: linkedin
ieeeMember: "IEEE Power & Energy Systems Society Member"
unileonMember: "PhD from León University"
linkedin_username: paco-aguayo
license: "MIT License"

# set to true to show excerpts on the homepage
show_excerpts: true 

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ 
minima:
  date_format: "%b %-d, %Y"



# Language labels
i18n:
  en:
    categories: "Categories"
    featured:   "Featured"
    download:   "Downloads"
    essay:      "JavaDoc & Guides"
    acknowledgment: "Acknowledgments" 
  es:
    categories: "Categorías"
    featured:   "Destacados"
    download:   "Descargas"
    essay:      "JavaDoc y Manuales"
    acknowledgment: "Agradecimientos"


plugins:
 - jekyll-feed
 - jekyll-seo-tag
